apiVersion: tekton.dev/v1alpha1
kind: Devfile
metadata:
  name: ansible-terraform-dev
spec:
  version: 0.1.0
  provider:
    name: devfile-registry.dev
    url: https://devfile.io
  components:
    - name: main
      image: mcr.microsoft.com/devcontainers/dev-shell:tizen
      container:
        ports:
          - name: vscode
            containerPort: 3000
            protocol: tcp
        volumeMounts:
          - name: workspace
            mountPath: /workspace
        extensions:
          - id: ms-vscode.vscode-remote-connect
            path: .devcontainer
          - id: redhat.ansible
          - id: hashicorp.terraform
          - id: ms-toolsai.continue
          - id: ms-python.python
          - id: ms-azuretools.vscode-azureaccount
          - id: ms-vscode.vscode-kubernetes-tools
      environment:
        - name: VSCODE_PORT
          value: "3000"
      commands:
        - name: terraform-init
          container: main
          args: ["terraform", "init"]
        - name: terraform-fmt
          container: main
          args: ["terraform", "fmt", "-check"]
        - name: ansible-lint
          container: main
          args: ["ansible-lint", "."]
        - name: ansible-playbook
          container: main
          args: ["ansible-playbook", "-i", "inventory", "site.yml"]
    - name: ollama
      image: ollama/ollama
      container:
        ports:
          - name: ollama-api
            containerPort: 11434
            protocol: tcp
        volumeMounts:
          - name: ollama-data
            mountPath: /root/.ollama
      resources:
        requests:
          memory: "4g"
        limits:
          memory: "8g"
    - name: git-credentials
      image: alpine/git
      container:
        volumeMounts:
          - name: git-config
            mountPath: /root/.gitconfig
      commands:
        - name: configure-git
          container: git-credentials
          args: ["git", "config", "--global", "user.email", "devspaces@example.com"]
  volumes:
    - name: workspace
      emptyDir: {}
    - name: git-config
      emptyDir: {}
    - name: ollama-data
      emptyDir: {}
